ui:
  enabled: true
  serviceType: "NodePort"

server:
  dev:
    enabled: true
    devRootToken: "root"
  logLevel: debug
  service:
    enabled: true
    type: NodePort
    nodePort: 30000

injector:
  enabled: "false"